version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017

  springboot-mongo-demo:
    image: gyarsilalsolanki011/springboot-mongo-demo
    container_name: "springboot-mongo-demo"
    ports:
      - 8080:8080
    links:
      - mymongodb